# Generated by Django 5.2 on 2025-07-05 00:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fecha_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
