# Generated by Django 5.2 on 2025-05-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
