# Generated by Django 5.1.4 on 2025-05-11 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_registro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
